#!/bin/bash
if [ -d "venv/bin" ]; then
    echo "Virtual environment already exists."
else
    if ! command -v virtualenv &> /dev/null; then
        echo "virtualenv could not be found. Attempting to install..."
        if ! command -v pip &> /dev/null; then
            echo "pip could not be found. Attempting to install..."
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py
            rm get-pip.py
        fi
        pip install virtualenv
    fi
    virtualenv -p python3 venv
    echo "Virtual environment created. Attempting to source..."
fi
