#!/bin/bash
# check if display is attached, if so then mirror the display, otherwise
# disable the display. 
if [[ $(xrandr | grep "HDMI-A-0 connected") = *"HDMI-A-0 connected"* ]]; then
        xrandr --newmode "Mirror" 312.25 2560 2752 3024 3488 1440 1443 1448 1493 -hsync +vsync
        xrandr --addmode HDMI-A-0 "Mirror"
        sleep 0.1
        #xrandr --output HDMI-A-0 --mode "Mirror" --same-as DisplayPort-0
        xrandr --output HDMI-A-0 --off
fi
