#!/bin/bash

wmst="~/projects/school/womens_studies/"
ds="~/projects/school/datastructures_and_algorithms/"
theory="~/projects/school/intro_to_theory/"
stats="~/projects/school/stats/"
if [ "$2" == "" ]; then
    echo "No file provided"
    exit 1
fi
filename=$(basename "$2")
case $1 in
    wmst)
        echo "moving to wmst"
        mv "$2" "$wmst"
        ;;
    theory)
        echo "moving to theory"
        mv "$2" "$theory"
        ;;
    stats)
        echo "moving to stats"
        mv "$2" "$stats"
        ;;
    ds)
        echo "moving to datastructures & algorithms"
        mv "$2" "$ds"
        ;;
    *)
        echo -n "Move a file directly to the specified class."
        echo -n "\$ classify [class tag] [file]"
        echo -n "tags:"
        echo -n "wmst   - Women's Studies                   $wmst"
        echo -n "theory - Theory of Computing               $theory"
        echo -n "stats  - Stats 2000                        $stats"
        echo -n "ds     - Datastructures and Algorithms     $ds"
        exit 1
        ;;
esac
