#!/usr/bin/env bash
# Usage
#================================================================
# HEADER
#================================================================
#% SYNOPSIS
#+    ${SCRIPT_NAME} | container name 
#%
#% DESCRIPTION
#%    Quickly open a shell in a running docker container
#%
#% OPTIONS
#%    -h, --help                    Print this help
#%
#% EXAMPLES
#%    ${SCRIPT_NAME} dimbus_dongus
#%    ${SCRIPT_NAME} Redis
#%
#================================================================
#- IMPLEMENTATION
#-    version         ${SCRIPT_NAME}  0.0.1
#-    author          Alex Teal
#-    copyright       (none)
#-    license         (none)
#-    script_id       2
#-
#================================================================
#  HISTORY
#     2022/08/27 : alexteal : Script creation
# 
#================================================================
#  DEBUG OPTION
#    set -n  # Uncomment to check your syntax, without execution.
#    set -x  # Uncomment to debug this shell script
#
#================================================================
# END_OF_HEADER
#================================================================
  #== needed variables ==#
SCRIPT_HEADSIZE=$(head -200 ${0} |grep -n "^# END_OF_HEADER" | cut -f1 -d:)
SCRIPT_NAME="$(basename ${0})"

  #== usage functions ==#
usage() { printf "Usage: "; head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#+" | sed -e "s/^#+[ ]*//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g" ; }
usagefull() { head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#[%+-]" | sed -e "s/^#[%+-]//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g" ; }
scriptinfo() { head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#-" | sed -e "s/^#-//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g"; }

case $1 in
    h )
        usagefull
        exit 0
        ;;

    *) 
    docker exec -it $1 /bin/bash
        ;;
esac
