#!/bin/bash
slug=$(date +%s)
count=$(ls $HOME/vimwiki/diary | wc -l| xargs)

cd $HOME/vimwiki/

gpgtar -o $HOME/vimwiki/diary$slug.gpg --yes -r $USER -e diary
bytes_new=$(wc -c $HOME/vimwiki/diary$slug.gpg)
bytes_old=$(wc -c $HOME/vimwiki/diary.gpg)
if [[ $count -gt 20 ]]; then
    if [[ "$?" == "0" ]]; then
        mv -f $HOME/vimwiki/diary$slug.gpg $HOME/vimwiki/diary.gpg
        rm -rf $HOME/vimwiki/diary
        echo [Locked]
    fi
else
    echo "[Error] Current diary contains $count items, much less than expected."
    echo "Check directory, trying to force this might cause file loss."
    echo "[Bytes]"
    echo "New archive: $bytes_new"
    echo "Old archive: $bytes_old"
    rm $HOME/vimwiki/diary$slug.gpg
    exit 1
fi 
