#!/bin/bash

#TODO
# USB Webserver doesn't start on the remarkable until a physical connection is 
# established. 
# Need to figure out a way to initiate webserver without physical connection
# Trick used below doesn't work. 

if [ -z "$1" ]; then
    echo "Usage is "
    echo "rm2web REMARKABLEHOSTNAME"
    exit 1
fi
# Incase something went wrong, go ahead and destroy the interface
ssh $1 ip addr flush dev usb0
# Assign IP address on the Remarkable to make xochitl believe
# the USB cable is attached, such that you can enable the server.
ssh $1 /sbin/ip addr add 10.11.99.1/32 dev usb0

# Assign same IP locally because the web server wants the proper
# Host header, so we cannot just use a port forwarding.
#sudo ip addr add 10.11.99.1/32 dev lo

# Open browser before because ssh will pause execution
# For some reason only apple Developers would know, this doesn't work in tmux.
# Use a new tty for this line to work
open http://127.0.0.1:8689

# SSH port forwarding (assumes you have ControlMaster enabled)
ssh -L 8689:10.11.99.1:8080 $1 -vvv -N
