#!/bin/bash
rm -rf $HOME/projects/.stignore
touch $HOME/projects/.stignore
default_ignore="// BEGIN Default Ignored folders
*.git**
*mypy_cache**
*node_modules**
.env**
*media**
**/venv/**
**venv/**
// END Default Ignore folders
"

# genuine gpt magic
find $HOME/projects -type d \( -name "node_modules" -o -name "venv" \) -prune -o -name ".git" -exec sh -c 'folder="${1##*/projects/}"; echo "${folder%/.git}/**" >> "$HOME/projects/.stignore"' _ {} \;

ls -1 "$HOME"/projects/ARCHIVE >> "$HOME"/projects/.stignore
