#!/bin/sh
rm -rf $HOME/projects/.stignore
touch $HOME/projects/.stignore
default_ignore="\
    .git*\n
    *mypy_cache**\n
    *node_modules**\n
    ARCHIVE**\n
    "
echo $default_ignore >> $HOME/projects/.stignore
for i in $HOME/projects/*; do
    if [[ -d "$i/.git" ]]; then
        echo \*${i:25}\*\* >> $HOME/projects/.stignore

        continue
    else
        for j in $i/*; do
            if [[ -d "$j/.git" ]]; then
                echo \*${j:25}\*\* >> $HOME/projects/.stignore
                continue
            fi
        done
        continue
    fi
done
