#!/bin/bash
rm -rf $HOME/projects/.stignore
touch $HOME/projects/.stignore
default_ignore="// BEGIN Default Ignored folders
*.git**
*mypy_cache**
*node_modules**
ARCHIVE**
.env**
*media**
// END Default Ignore folders
"
#echo "$default_ignore" >> "$HOME/projects/.stignore"
#for i in $HOME/projects/*; do
#    if [[ -d "$i/.git" ]]; then
#        echo "*${i:25}**" >> "$HOME/projects/.stignore"
#
#        continue
#    else
#        for j in $i/*; do
#            if [[ -d "$j/.git" ]]; then
#                echo "*${j:25}**" >> "$HOME/projects/.stignore"
#                continue
#            fi
#        done
#        continue
#    fi
#done
echo "$default_ignore" >> "$HOME/projects/.stignore"
for i in $HOME/projects/*; do
    if [[ -d "$i/.git" ]]; then
        folder_path="${i##*/}"
        echo "*$folder_path**" >> "$HOME/projects/.stignore"
        continue
    else
        git_dir=$(find "$i" -type d -name ".git" -print -quit)
        if [[ -n "$git_dir" ]]; then
            folder_path="${i##*/}"
            echo "*$folder_path**" >> "$HOME/projects/.stignore"
            continue
        fi
    fi
done

