#!/bin/bash
gpgtar --decrypt -r diary -C $HOME/vimwiki/ $HOME/vimwiki/diary.gpg
if [[ "$?" == "1" ]]; then
    exit 1
fi
slug=$(ls $HOME/vimwiki/ | grep 'diary\d\d\d'| cut -d 'y' -f 2)
mkdir -p "$HOME/vimwiki/diary"
mv $HOME/vimwiki/diary$slug/* $HOME/vimwiki/diary/
rm -rf "$HOME/vimwiki/diary$slug"
