#!/bin/bash
# Check if venv directory exists
if [ -d "./venv/bin" ]
then
  echo "sourced local ./venv"
  source ./venv/bin/activate
else
  echo "Virtual environment does not exist. Creating one..."
  python3 -m venv venv
  # Activate the virtual environment
  source ./venv/bin/activate
fi
